/*
 * Copyright (C) 2013 Thiago Henque Bonotto da Silva & Gustavo Constante
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package poo;

/**
 * Classe que gerencia a tela de batalha encaminha os métodos que devem serem efetuados.
 * 
 * @author Gustavo Constante
 * @author Thiago Henrique Bonotto da Silva
 */
public class BattleMenuDown extends javax.swing.JPanel {
    GUIMain parent;
   
    /**
     * Creates new form JavaMonBattleMenuDown
     */
    public BattleMenuDown(GUIMain p) {
        initComponents();
        this.parent =p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTrocarPokemon = new javax.swing.JButton();
        jBAFt1 = new javax.swing.JButton();
        jBAFt2 = new javax.swing.JButton();
        jBAfraco2 = new javax.swing.JButton();
        jBAfraco1 = new javax.swing.JButton();
        jBItem2 = new javax.swing.JButton();
        jBItem1 = new javax.swing.JButton();

        jBTrocarPokemon.setText("Trocar Pokemon");
        jBTrocarPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTrocarPokemonActionPerformed(evt);
            }
        });

        jBAFt1.setText("Ataque forte1");
        jBAFt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAFt1ActionPerformed(evt);
            }
        });

        jBAFt2.setText("Ataque forte 2");
        jBAFt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAFt2ActionPerformed(evt);
            }
        });

        jBAfraco2.setText("Ataque fraco 2");
        jBAfraco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAfraco2ActionPerformed(evt);
            }
        });

        jBAfraco1.setText("Ataque fraco 1");
        jBAfraco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAfraco1ActionPerformed(evt);
            }
        });

        jBItem2.setText("Item 2");
        jBItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBItem2ActionPerformed(evt);
            }
        });

        jBItem1.setText("Item 1");
        jBItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBItem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jBItem1)
                .addGap(24, 24, 24)
                .addComponent(jBItem2)
                .addGap(14, 14, 14)
                .addComponent(jBAFt1)
                .addGap(14, 14, 14)
                .addComponent(jBAFt2))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBTrocarPokemon)
                .addGap(16, 16, 16)
                .addComponent(jBAfraco1)
                .addGap(10, 10, 10)
                .addComponent(jBAfraco2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBItem1)
                    .addComponent(jBItem2)
                    .addComponent(jBAFt1)
                    .addComponent(jBAFt2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBTrocarPokemon)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAfraco1)
                            .addComponent(jBAfraco2)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBTrocarPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTrocarPokemonActionPerformed
        // TODO add your handling code here:
        parent.trocarPokemon();
        enableAll(false);
    }//GEN-LAST:event_jBTrocarPokemonActionPerformed

    private void jBItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBItem1ActionPerformed
        // TODO add your handling code here:
        
        parent.personagemAtual.setItem1(false);
        enableAll(false);
        parent.ct.enviarMensagem(new Mensagem(320, "item 1"));
        
    }//GEN-LAST:event_jBItem1ActionPerformed

    private void jBItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBItem2ActionPerformed
        // TODO add your handling code here:
      
        parent.personagemAtual.setItem2(false);
        enableAll(false);
        parent.ct.enviarMensagem(new Mensagem(321, "item 2"));
        
    }//GEN-LAST:event_jBItem2ActionPerformed

    private void jBAFt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAFt1ActionPerformed
        // TODO add your handling code here:
        parent.ct.enviarMensagem(new Mensagem(301, "ataque forte 1"));
        enableAll(false);
    }//GEN-LAST:event_jBAFt1ActionPerformed

    private void jBAFt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAFt2ActionPerformed
        // TODO add your handling code here:
        parent.ct.enviarMensagem(new Mensagem(311, "ataque forte 2"));
        enableAll(false);
    }//GEN-LAST:event_jBAFt2ActionPerformed

    private void jBAfraco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAfraco1ActionPerformed
        // TODO add your handling code here:
        parent.ct.enviarMensagem(new Mensagem(312, "ataque fraco 1"));
        enableAll(false);
    }//GEN-LAST:event_jBAfraco1ActionPerformed

    private void jBAfraco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAfraco2ActionPerformed
        // TODO add your handling code here:
        parent.ct.enviarMensagem(new Mensagem(313, "ataque fraco 2"));
        enableAll(false);
    }//GEN-LAST:event_jBAfraco2ActionPerformed
    public void enableAll(boolean b){
        this.jBTrocarPokemon.setEnabled(b);
        if(parent.personagemAtual.isItem1() && b){        
        this.jBItem1.setEnabled(true);
        }else{
            this.jBItem1.setEnabled(false);
        }
        if(parent.personagemAtual.isItem2() && b){
        this.jBItem2.setEnabled(true);
        } else{
            this.jBItem2.setEnabled(false);
        }
        this.jBAfraco1.setEnabled(b);
        this.jBAfraco2.setEnabled(b);
        this.jBAFt1.setEnabled(b);
        this.jBAFt2.setEnabled(b);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAFt1;
    private javax.swing.JButton jBAFt2;
    private javax.swing.JButton jBAfraco1;
    private javax.swing.JButton jBAfraco2;
    private javax.swing.JButton jBItem1;
    private javax.swing.JButton jBItem2;
    private javax.swing.JButton jBTrocarPokemon;
    // End of variables declaration//GEN-END:variables
}
