/*
 * Copyright (C) 2013 Thiago Henque Bonotto da Silva & Gustavo Constante
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package poo;

import poo.Personagens.Personagem;

/**
 * Classe 
 * @author Thiago Henrique Bonotto da Silva
 * @author Gustavo Constante
 */
public class BattleMenu extends javax.swing.JPanel {
    GUIMain parent;
    
    public BattleMenu(GUIMain p) {
        initComponents();
        this.parent = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBCostasPlayer = new javax.swing.JProgressBar();
        jLCostasHp = new java.awt.Label();
        jPBFrentePlayer = new javax.swing.JProgressBar();
        jLFrenteHp = new java.awt.Label();
        jBCostasPlayer = new javax.swing.JButton();
        jBFrentePlayer = new javax.swing.JButton();
        jLCostasNome = new java.awt.Label();
        jLFrenteNome = new java.awt.Label();

        jPBCostasPlayer.setValue(100);

        jLCostasHp.setText("label1");

        jPBFrentePlayer.setForeground(new java.awt.Color(30, 120, 15));
        jPBFrentePlayer.setValue(100);

        jLFrenteHp.setText("label2");

        jBCostasPlayer.setText("jButton1");
        jBCostasPlayer.setEnabled(false);

        jBFrentePlayer.setText("jButton1");
        jBFrentePlayer.setEnabled(false);
        jBFrentePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFrentePlayerActionPerformed(evt);
            }
        });

        jLCostasNome.setText("label1");

        jLFrenteNome.setText("label2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jPBFrentePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFrentePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFrenteHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFrenteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPBCostasPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jBCostasPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCostasNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCostasHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPBFrentePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFrentePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLFrenteHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLFrenteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jPBCostasPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCostasPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLCostasNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLCostasHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBFrentePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFrentePlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFrentePlayerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCostasPlayer;
    private javax.swing.JButton jBFrentePlayer;
    private java.awt.Label jLCostasHp;
    private java.awt.Label jLCostasNome;
    private java.awt.Label jLFrenteHp;
    private java.awt.Label jLFrenteNome;
    private javax.swing.JProgressBar jPBCostasPlayer;
    private javax.swing.JProgressBar jPBFrentePlayer;
    // End of variables declaration//GEN-END:variables

    void setJg1Pokemon(Personagem p) {
        jBCostasPlayer.setDisabledIcon(p.getIcon_costas());
        jLCostasNome.setText(p.getNome());
     }
    

    void setJg2Pokemon(Personagem p) {
       jBFrentePlayer.setDisabledIcon(p.getIcon_frente());
        jLFrenteNome.setText(p.getNome());
    }

    void setJg1Hp(String string) {
        jPBCostasPlayer.setValue(Integer.parseInt(string));
         jLCostasHp.setText(string);
    }

    void setJg2Hp(String string) {
        jPBFrentePlayer.setValue(Integer.parseInt(string));
        jLFrenteHp.setText(string);
    }
}
