/*
 * Copyright (C) 2013 Thiago Henque Bonotto da Silva & Gustavo Constante
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package poo;

import poo.Personagens.Personagem;

/**
 * Classe responsavel pela troca de personagens durante a partida, mostrando o icone e a vida que os personagens estão
 * 
 * @author Thiago Henque Bonotto da Silva
 * @author Gustavo Constante
 */
public class ChangeMenu extends javax.swing.JPanel {

    GUIMain parent;

    /**
     * Cria a tela de ChangeMenu
     *
     * @param parent Referencia ao pai.
     * @param p Recebe o vetor de personagens disponiveis para troca.
     * @param a Recebe o personagem atual para evitar de selecionar o mesmo na
     * troca.
     */
    @SuppressWarnings("empty-statement")
    public ChangeMenu(GUIMain parent, Personagem[] p) {
        initComponents();
        this.parent = parent;        
        this.jBEscolhido1.setIcon(p[0].getIcon_escolha());
        this.jLNome1.setText(p[0].getNome());
        this.jLHp1.setText(Integer.toString(p[0].getHp()));
        this.jBEscolhido2.setIcon(p[1].getIcon_escolha());
        this.jLNome2.setText(p[1].getNome());
        this.jLHp2.setText(Integer.toString(p[1].getHp()));
        this.jBEscolhido3.setIcon(p[2].getIcon_escolha());
        this.jLNome3.setText(p[2].getNome());
        this.jLHp3.setText(Integer.toString(p[2].getHp()));
        this.jBEscolhido4.setIcon(p[3].getIcon_escolha());
        this.jLNome4.setText(p[3].getNome());
        this.jLHp4.setText(Integer.toString(p[3].getHp()));
        this.jBEscolhido5.setIcon(p[4].getIcon_escolha());
        this.jLNome5.setText(p[4].getNome());
        this.jLHp5.setText(Integer.toString(p[4].getHp()));
        this.jBEscolhido6.setIcon(p[5].getIcon_escolha());
        this.jLNome6.setText(p[5].getNome());
        this.jLHp6.setText(Integer.toString(p[5].getHp()));
        if ("0".equals(jLHp1.getText()) || p[0].equals(parent.getPersonagemAtual())) {
            jBEscolhido1.setEnabled(false);
        }
        if ("0".equals(jLHp2.getText())|| p[1].equals(parent.getPersonagemAtual())) {
            jBEscolhido2.setEnabled(false);
        }
        if ("0".equals(jLHp3.getText())|| p[2].equals(parent.getPersonagemAtual())) {
            jBEscolhido3.setEnabled(false);
        }
        if ("0".equals(jLHp4.getText())|| p[3].equals(parent.getPersonagemAtual())) {
            jBEscolhido4.setEnabled(false);
        }
        if ("0".equals(jLHp5.getText())|| p[4].equals(parent.getPersonagemAtual())) {
            jBEscolhido5.setEnabled(false);
        }
         if ("0".equals(jLHp6.getText())|| p[5].equals(parent.getPersonagemAtual())) {
            jBEscolhido6.setEnabled(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEscolhidos = new javax.swing.JPanel();
        jBEscolhido1 = new javax.swing.JButton();
        jBEscolhido2 = new javax.swing.JButton();
        jBEscolhido3 = new javax.swing.JButton();
        jBEscolhido4 = new javax.swing.JButton();
        jBEscolhido6 = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLNome1 = new javax.swing.JLabel();
        jLHp1 = new javax.swing.JLabel();
        jLNome2 = new javax.swing.JLabel();
        jLNome3 = new javax.swing.JLabel();
        jLNome4 = new javax.swing.JLabel();
        jLNome5 = new javax.swing.JLabel();
        jLHp2 = new javax.swing.JLabel();
        jLHp3 = new javax.swing.JLabel();
        jLHp4 = new javax.swing.JLabel();
        jLHp5 = new javax.swing.JLabel();
        jLNome6 = new javax.swing.JLabel();
        jLHp6 = new javax.swing.JLabel();
        jBEscolhido5 = new javax.swing.JButton();

        jPEscolhidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBEscolhido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhido1ActionPerformed(evt);
            }
        });

        jBEscolhido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhido2ActionPerformed(evt);
            }
        });

        jBEscolhido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhido3ActionPerformed(evt);
            }
        });

        jBEscolhido4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhido4ActionPerformed(evt);
            }
        });

        jBEscolhido6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhido6ActionPerformed(evt);
            }
        });

        jBVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLNome1.setText("Nome");

        jLHp1.setText("Vida");

        jLNome2.setText("Nome");

        jLNome3.setText("Nome");

        jLNome4.setText("Nome");

        jLNome5.setText("Nome");

        jLHp2.setText("Vida");

        jLHp3.setText("Vida");

        jLHp4.setText("Vida");

        jLHp5.setText("Vida");

        jLNome6.setText("Nome");

        jLHp6.setText("Vida");

        jBEscolhido5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhido5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEscolhidosLayout = new javax.swing.GroupLayout(jPEscolhidos);
        jPEscolhidos.setLayout(jPEscolhidosLayout);
        jPEscolhidosLayout.setHorizontalGroup(
            jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                                .addComponent(jBEscolhido1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBEscolhido2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                                .addComponent(jLHp1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLHp2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLHp3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLHp4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLHp5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBVoltar)
                                    .addComponent(jBEscolhido3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBEscolhido4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBEscolhido5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addComponent(jLNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLHp6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEscolhido6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEscolhidosLayout.setVerticalGroup(
            jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEscolhido2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBVoltar)
                        .addGap(6, 6, 6))
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHp1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHp2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHp4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHp5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHp3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHp6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEscolhidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEscolhidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBEscolhido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhido1ActionPerformed
        // TODO add your handling code here:
        parent.setBattlePersonagem(jLNome1.getText());
        parent.alteraPanel(parent.battleMenu, parent.jPMenuEsq);


    }//GEN-LAST:event_jBEscolhido1ActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        parent.alteraPanel(parent.battleMenu, parent.jPMenuEsq);
        parent.battleMenuDown.enableAll(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBEscolhido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhido2ActionPerformed
        // TODO add your handling code here:
        parent.setBattlePersonagem(jLNome2.getText());
        parent.alteraPanel(parent.battleMenu, parent.jPMenuEsq);

    }//GEN-LAST:event_jBEscolhido2ActionPerformed

    private void jBEscolhido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhido3ActionPerformed
        // TODO add your handling code here:
        parent.setBattlePersonagem(jLNome3.getText());
        parent.alteraPanel(parent.battleMenu, parent.jPMenuEsq);

    }//GEN-LAST:event_jBEscolhido3ActionPerformed

    private void jBEscolhido4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhido4ActionPerformed
        // TODO add your handling code here:
        parent.setBattlePersonagem(jLNome4.getText());
        parent.alteraPanel(parent.battleMenu, parent.jPMenuEsq);

    }//GEN-LAST:event_jBEscolhido4ActionPerformed

    private void jBEscolhido6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhido6ActionPerformed
        // TODO add your handling code here:
        parent.setBattlePersonagem(jLNome6.getText());
        parent.alteraPanel(parent.battleMenu, parent.jPMenuEsq);

    }//GEN-LAST:event_jBEscolhido6ActionPerformed

    private void jBEscolhido5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhido5ActionPerformed
        // TODO add your handling code here:
         parent.setBattlePersonagem(jLNome5.getText());
        parent.alteraPanel(parent.battleMenu, parent.jPMenuEsq);
    }//GEN-LAST:event_jBEscolhido5ActionPerformed
    public void habilitaVoltar(boolean b) {
        this.jBVoltar.setEnabled(b);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEscolhido1;
    private javax.swing.JButton jBEscolhido2;
    private javax.swing.JButton jBEscolhido3;
    private javax.swing.JButton jBEscolhido4;
    private javax.swing.JButton jBEscolhido5;
    private javax.swing.JButton jBEscolhido6;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLHp1;
    private javax.swing.JLabel jLHp2;
    private javax.swing.JLabel jLHp3;
    private javax.swing.JLabel jLHp4;
    private javax.swing.JLabel jLHp5;
    private javax.swing.JLabel jLHp6;
    private javax.swing.JLabel jLNome1;
    private javax.swing.JLabel jLNome2;
    private javax.swing.JLabel jLNome3;
    private javax.swing.JLabel jLNome4;
    private javax.swing.JLabel jLNome5;
    private javax.swing.JLabel jLNome6;
    private javax.swing.JPanel jPEscolhidos;
    // End of variables declaration//GEN-END:variables
}
