/*
 * Copyright (C) 2013 Thiago Henque Bonotto da Silva & Gustavo Constante
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package poo;

import cliente.ClienteThread;


/**
 * Classe responsavel por criar e iniciar o chat
 * 
 * @author Thiago Henrique Bonotto da Silva
 * @author Gustavo Constante
 */
public class  ChatMenu extends javax.swing.JPanel {

  private ClienteThread ct;
  private String nick;

    public static void habilitarChat() {
        jTAMensagens.setEnabled(true);
        jBEnviarMensagem.setEnabled(true);
        jTFChat.setEnabled(true);
    }

    /**
     * Cria um ChatMenu
     *
     * @param nick
     */
    public ChatMenu(String nick) {
        initComponents();
        this.nick = nick;

    }
    
    /**
     * Método que seta um ClienteThread ao cliente que se logou no servidor
     * @param ct
     */
    public void setCT(ClienteThread ct){
        this.ct = ct;
    }
    
    /**
     * Método que adiciona as mensagens na janela do chat
     * @param msg
     */
    public void adicionarLinha(String msg) {

        //jTAMensagens.insert(msg + "\n", 0);
        jTAMensagens.append(msg + "\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBEnviarMensagem = new javax.swing.JButton();
        jTFChat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAMensagens = new javax.swing.JTextArea();

        jBEnviarMensagem.setText("Enviar");
        jBEnviarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarMensagemActionPerformed(evt);
            }
        });

        jTFChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFChatActionPerformed(evt);
            }
        });
        jTFChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFChatKeyPressed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setEnabled(false);

        jTAMensagens.setEditable(false);
        jTAMensagens.setColumns(20);
        jTAMensagens.setRows(5);
        jScrollPane1.setViewportView(jTAMensagens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jBEnviarMensagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTFChat, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEnviarMensagem))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnviarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarMensagemActionPerformed
        // TODO add your handling code here:
        String msg = jTFChat.getText();
        ct.enviarMensagem(new Mensagem(110, msg));
        this.adicionarLinha(nick + ":\n" + msg);
        jTFChat.setText("");
        jTFChat.requestFocus();


    }//GEN-LAST:event_jBEnviarMensagemActionPerformed

    private void jTFChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFChatKeyPressed
        // TODO add your handling code here:
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){     
                  jBEnviarMensagemActionPerformed(null);
        }  
    }//GEN-LAST:event_jTFChatKeyPressed

    private void jTFChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFChatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jBEnviarMensagem;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTAMensagens;
    private static javax.swing.JTextField jTFChat;
    // End of variables declaration//GEN-END:variables
}
