/*
 * Copyright (C) 2013 Thiago Henque Bonotto da Silva & Gustavo Constante
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package poo;

/**
 * Classe incial do Menu Esquerdo ele inicia uma imagem do jogo e um local
 * para inserir o nickname
 *
 * @author Gustavo Constante
 * @author Thiago Henrique Bonotto da Silva
 */
public class FirstMenuEsq extends javax.swing.JPanel {

    /**
     * Cria tela FirstMenuEsq
     */
    public FirstMenuEsq() {
        initComponents();
    }

    /**
     * Método para pegar o nickname da label e enviar para
     * o servidor posteriormente
     * 
     * @return
     */
    public String getNickName() {
        return this.jTFNickName.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenuEsq = new javax.swing.JPanel();
        jLImagem = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFNickName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jPMenuEsq.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inicial.jpg"))); // NOI18N

        jLabel6.setText("Nickname:");

        jTFNickName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNickNameActionPerformed(evt);
            }
        });

        jLabel7.setText("JavaMon 1.1");

        javax.swing.GroupLayout jPMenuEsqLayout = new javax.swing.GroupLayout(jPMenuEsq);
        jPMenuEsq.setLayout(jPMenuEsqLayout);
        jPMenuEsqLayout.setHorizontalGroup(
            jPMenuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuEsqLayout.createSequentialGroup()
                .addComponent(jLImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(79, 79, 79))
            .addGroup(jPMenuEsqLayout.createSequentialGroup()
                .addGroup(jPMenuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMenuEsqLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jTFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMenuEsqLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPMenuEsqLayout.setVerticalGroup(
            jPMenuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuEsqLayout.createSequentialGroup()
                .addGroup(jPMenuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPMenuEsqLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPMenuEsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenuEsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNickNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNickNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNickNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLImagem;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel jPMenuEsq;
    public javax.swing.JTextField jTFNickName;
    // End of variables declaration//GEN-END:variables
}
