/*
 * Copyright (C) 2013 vendetta.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */

package poo;

import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * Classe que gerencia as informações do tela inicial do jogo que contem informações
 * como IP, porta do servidor, porta do cliente e encaminha para as rotinas de criação de servidor ou
 * logar em um determinado servidor.
 * 
 * @author Thiago Henrique Bonotto da Silva
 * @author Gustavo Constante
 */
public class FistMenuDown extends javax.swing.JPanel {
    GUIMain parent;
    /**
     * Creates new form FistMenuDown
     */
    public FistMenuDown(GUIMain p) {
        initComponents();
        this.parent = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenuDown = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBConectar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jBServidor = new javax.swing.JButton();
        jTFClienteIp = new javax.swing.JTextField();
        jTFClientePorta = new javax.swing.JTextField();
        jTFServidorPorta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPMenuDown.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Cliente");

        jBConectar.setText("Conectar");
        jBConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConectarActionPerformed(evt);
            }
        });

        jLabel3.setText("IP:");

        jLabel4.setText("Porta:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Servidor");

        jBServidor.setText("Criar Servidor");
        jBServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBServidorActionPerformed(evt);
            }
        });

        jTFClienteIp.setText("localhost");
        jTFClienteIp.setAutoscrolls(false);
        jTFClienteIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFClienteIpActionPerformed(evt);
            }
        });

        jTFClientePorta.setText("1234");

        jTFServidorPorta.setText("1234");

        jLabel1.setText("Porta:");

        javax.swing.GroupLayout jPMenuDownLayout = new javax.swing.GroupLayout(jPMenuDown);
        jPMenuDown.setLayout(jPMenuDownLayout);
        jPMenuDownLayout.setHorizontalGroup(
            jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuDownLayout.createSequentialGroup()
                .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPMenuDownLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPMenuDownLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuDownLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)))
                        .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBConectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFClientePorta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFClienteIp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMenuDownLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuDownLayout.createSequentialGroup()
                        .addGap(52, 55, Short.MAX_VALUE)
                        .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuDownLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFServidorPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuDownLayout.createSequentialGroup()
                                .addComponent(jBServidor)
                                .addContainerGap())))))
        );
        jPMenuDownLayout.setVerticalGroup(
            jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuDownLayout.createSequentialGroup()
                .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPMenuDownLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFServidorPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jBServidor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPMenuDownLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFClienteIp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPMenuDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFClientePorta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBConectar)
                        .addGap(12, 12, 12))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPMenuDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenuDown, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Retorna o IP em que o cliente deve se conectar
     * 
     * @return
     */
    public String getClienteIp(){
        return this.jTFClienteIp.getText();
    }
    
    /**
     * Retorna a porta em que o cliente deve se conectar e encaminhar as mensagens
     * @return
     */
    public int getClientePorta(){
        return Integer.parseInt(this.jTFClientePorta.getText());
    }
    
    /**
     * Retorna a porta que o servidor deve ficar escutando o recebimento das mensagens
     * @return
     */
    public int getServidorPorta(){
        return Integer.parseInt(this.jTFServidorPorta.getText());
    }
    
    private void jBConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConectarActionPerformed
        // TODO add your handling code here:
        parent.conectouServidor();
    }//GEN-LAST:event_jBConectarActionPerformed

    private void jBServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBServidorActionPerformed
        try {
            // TODO add your handling code here:
           
            parent.criarServidor();
        } catch (InterruptedException ex) {
            Logger.getLogger(FistMenuDown.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBServidorActionPerformed

    private void jTFClienteIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFClienteIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFClienteIpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConectar;
    private javax.swing.JButton jBServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPMenuDown;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTFClienteIp;
    private javax.swing.JTextField jTFClientePorta;
    private javax.swing.JTextField jTFServidorPorta;
    // End of variables declaration//GEN-END:variables
}
