/*
 * Copyright (C) 2013 Thiago Henque Bonotto da Silva & Gustavo Constante
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package poo;

//<editor-fold defaultstate="collapsed" desc="Import's">
import poo.Personagens.Personagem;
import poo.Personagens.Ponyta;
//</editor-fold>

/**
 * Javadoc da Rotina de selecionar Personagens
 *
 * @author Gustavo Constante
 * @author Thiago Henrique Bonotto da Silva
 * 
 */
public class PickMenu extends javax.swing.JPanel {

    public GUIMain parent;
    private int n;

//<editor-fold defaultstate="collapsed" desc="Método de iniciar tela de escolha de personagens">
    /**
     * Cria tela de PickMenu
     *
     * @param p
     */
    public PickMenu(GUIMain p) {
        initComponents();
        this.parent = p;
    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPersonagens = new javax.swing.JPanel();
        jLPrsonagens = new javax.swing.JLabel();
        jBPersonagem1 = new javax.swing.JButton();
        jBPersonagem2 = new javax.swing.JButton();
        jBPersonagem3 = new javax.swing.JButton();
        jBPersonagem4 = new javax.swing.JButton();
        jBPersonagem5 = new javax.swing.JButton();
        jBPersonagem6 = new javax.swing.JButton();
        jBPersonagem7 = new javax.swing.JButton();
        jBPersonagem8 = new javax.swing.JButton();
        jBPersonagem9 = new javax.swing.JButton();
        jBPersonagem10 = new javax.swing.JButton();
        jLPokemonNome = new javax.swing.JLabel();

        jPPersonagens.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLPrsonagens.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLPrsonagens.setText("Escolha seus Personagens:");

        jBPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ponyta_escolha.png"))); // NOI18N
        jBPersonagem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem1MouseEntered(evt);
            }
        });
        jBPersonagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem1ActionPerformed(evt);
            }
        });

        jBPersonagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shellder_escolha.png"))); // NOI18N
        jBPersonagem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem2MouseEntered(evt);
            }
        });
        jBPersonagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem2ActionPerformed(evt);
            }
        });

        jBPersonagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bulbasaur_escolha.png"))); // NOI18N
        jBPersonagem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem3MouseEntered(evt);
            }
        });
        jBPersonagem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem3ActionPerformed(evt);
            }
        });

        jBPersonagem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/goldeen_escolha.png"))); // NOI18N
        jBPersonagem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem4MouseEntered(evt);
            }
        });
        jBPersonagem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem4ActionPerformed(evt);
            }
        });

        jBPersonagem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/geodude_escolha.png"))); // NOI18N
        jBPersonagem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem5MouseEntered(evt);
            }
        });
        jBPersonagem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem5ActionPerformed(evt);
            }
        });

        jBPersonagem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hoothoot_escolha.png"))); // NOI18N
        jBPersonagem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem6MouseEntered(evt);
            }
        });
        jBPersonagem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem6ActionPerformed(evt);
            }
        });

        jBPersonagem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caterpie_escolha.png"))); // NOI18N
        jBPersonagem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem7MouseEntered(evt);
            }
        });
        jBPersonagem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem7ActionPerformed(evt);
            }
        });

        jBPersonagem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sandshrew_escolha.png"))); // NOI18N
        jBPersonagem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem8MouseEntered(evt);
            }
        });
        jBPersonagem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem8ActionPerformed(evt);
            }
        });

        jBPersonagem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pikachu_escolha.png"))); // NOI18N
        jBPersonagem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem9MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem9MouseEntered(evt);
            }
        });
        jBPersonagem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem9ActionPerformed(evt);
            }
        });

        jBPersonagem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mankey_escolha.png"))); // NOI18N
        jBPersonagem10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPersonagem10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPersonagem10MouseEntered(evt);
            }
        });
        jBPersonagem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPersonagem10ActionPerformed(evt);
            }
        });

        jLPokemonNome.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLPokemonNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPPersonagensLayout = new javax.swing.GroupLayout(jPPersonagens);
        jPPersonagens.setLayout(jPPersonagensLayout);
        jPPersonagensLayout.setHorizontalGroup(
            jPPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPersonagensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPersonagensLayout.createSequentialGroup()
                        .addComponent(jBPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPersonagensLayout.createSequentialGroup()
                        .addComponent(jLPrsonagens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLPokemonNome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPersonagensLayout.createSequentialGroup()
                        .addComponent(jBPersonagem6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPPersonagensLayout.setVerticalGroup(
            jPPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPersonagensLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPrsonagens)
                    .addComponent(jLPokemonNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPersonagensLayout.createSequentialGroup()
                        .addComponent(jBPersonagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPersonagensLayout.createSequentialGroup()
                        .addComponent(jBPersonagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPersonagensLayout.createSequentialGroup()
                        .addComponent(jBPersonagem5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPersonagem10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPersonagensLayout.createSequentialGroup()
                        .addGroup(jPPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBPersonagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPPersonagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBPersonagem6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPersonagem7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLPokemonNome.getAccessibleContext().setAccessibleName("jLPokemonNome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPPersonagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPPersonagens, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//<editor-fold defaultstate="collapsed" desc="Rotina de Adicionar Personagem">
    /**
     * Método para adicionar um personagem selecionado na lista e desabilita os
     * botões de pick se ja houver sido selecionado 6 personagens
     *
     * @param p
     */
    public void addPokemon(Personagem p) {
        if (n == 5) {
            enableAll(false);
        }
        parent.adicionaPokemon(p);
        n++;

    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Habilita todos os botões">
    /**
     * Habilita todos os botões da tela de escolha de personagens
     *
     * @param b
     */
    public void enableAll(boolean b) {
        jBPersonagem1.setEnabled(b);
        jBPersonagem2.setEnabled(b);
        jBPersonagem3.setEnabled(b);
        jBPersonagem4.setEnabled(b);
        jBPersonagem5.setEnabled(b);
        jBPersonagem6.setEnabled(b);
        jBPersonagem7.setEnabled(b);
        jBPersonagem8.setEnabled(b);
        jBPersonagem9.setEnabled(b);
        jBPersonagem10.setEnabled(b);
    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Chama o método para habilitar botões">
    /**
     * Chama o método para habilitar todos os botões do pick e limpa o variavel
     * que conta quantos personagens ja foram selecionados
     */
    public void resetaPick() {
        n = 0;
        enableAll(true);

    }
//</editor-fold>

    private void jBPersonagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem1ActionPerformed
        addPokemon(parent.personagens[0]);
        jBPersonagem1.setEnabled(false);

    }//GEN-LAST:event_jBPersonagem1ActionPerformed

    private void jBPersonagem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem1MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem1.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[0].getNome());
        }
    }//GEN-LAST:event_jBPersonagem1MouseEntered

    private void jBPersonagem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem1MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem1MouseExited

private void jBPersonagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem2ActionPerformed
    addPokemon(parent.personagens[1]);
    jBPersonagem2.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem2ActionPerformed

    private void jBPersonagem2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem2MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem2.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[1].getNome());
        }
    }//GEN-LAST:event_jBPersonagem2MouseEntered

    private void jBPersonagem2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem2MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem2MouseExited

private void jBPersonagem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem3ActionPerformed
    addPokemon(parent.personagens[2]);
    jBPersonagem3.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem3ActionPerformed

    private void jBPersonagem3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem3MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem3.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[2].getNome());
        }
    }//GEN-LAST:event_jBPersonagem3MouseEntered

    private void jBPersonagem3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem3MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem3MouseExited

private void jBPersonagem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem4ActionPerformed
    addPokemon(parent.personagens[3]);
    jBPersonagem4.setEnabled(false);

    }//GEN-LAST:event_jBPersonagem4ActionPerformed

    private void jBPersonagem4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem4MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem4.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[3].getNome());
        }
    }//GEN-LAST:event_jBPersonagem4MouseEntered

    private void jBPersonagem4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem4MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem4MouseExited

private void jBPersonagem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem5ActionPerformed
    addPokemon(parent.personagens[4]);
    jBPersonagem5.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem5ActionPerformed

    private void jBPersonagem5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem5MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem5.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[4].getNome());
        }
    }//GEN-LAST:event_jBPersonagem5MouseEntered

    private void jBPersonagem5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem5MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem5MouseExited

private void jBPersonagem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem6ActionPerformed
    addPokemon(parent.personagens[5]);
    jBPersonagem6.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem6ActionPerformed

    private void jBPersonagem6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem6MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem6.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[5].getNome());
        }
    }//GEN-LAST:event_jBPersonagem6MouseEntered

    private void jBPersonagem6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem6MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem6MouseExited

private void jBPersonagem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem7ActionPerformed
    addPokemon(parent.personagens[6]);
    jBPersonagem7.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem7ActionPerformed

    private void jBPersonagem7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem7MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem7.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[6].getNome());
        }
    }//GEN-LAST:event_jBPersonagem7MouseEntered

    private void jBPersonagem7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem7MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem7MouseExited

private void jBPersonagem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem8ActionPerformed
    addPokemon(parent.personagens[7]);
    jBPersonagem8.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem8ActionPerformed

    private void jBPersonagem8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem8MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem8.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[7].getNome());
        }
    }//GEN-LAST:event_jBPersonagem8MouseEntered

    private void jBPersonagem8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem8MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem8MouseExited

private void jBPersonagem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem9ActionPerformed
    addPokemon(parent.personagens[8]);
    jBPersonagem9.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem9ActionPerformed

    private void jBPersonagem9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem9MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem9.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[8].getNome());
        }
    }//GEN-LAST:event_jBPersonagem9MouseEntered

    private void jBPersonagem9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem9MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem9MouseExited

private void jBPersonagem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPersonagem10ActionPerformed
    addPokemon(parent.personagens[9]);
    jBPersonagem10.setEnabled(false);
    }//GEN-LAST:event_jBPersonagem10ActionPerformed

    private void jBPersonagem10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem10MouseEntered
        // TODO add your handling code here:
        if (jBPersonagem10.isEnabled()) {
            jLPokemonNome.setText(parent.personagens[9].getNome());
        }
    }//GEN-LAST:event_jBPersonagem10MouseEntered

    private void jBPersonagem10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPersonagem10MouseExited
        // TODO add your handling code here:
        jLPokemonNome.setText("");
    }//GEN-LAST:event_jBPersonagem10MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPersonagem1;
    private javax.swing.JButton jBPersonagem10;
    private javax.swing.JButton jBPersonagem2;
    private javax.swing.JButton jBPersonagem3;
    private javax.swing.JButton jBPersonagem4;
    private javax.swing.JButton jBPersonagem5;
    private javax.swing.JButton jBPersonagem6;
    private javax.swing.JButton jBPersonagem7;
    private javax.swing.JButton jBPersonagem8;
    private javax.swing.JButton jBPersonagem9;
    private javax.swing.JLabel jLPokemonNome;
    private javax.swing.JLabel jLPrsonagens;
    private javax.swing.JPanel jPPersonagens;
    // End of variables declaration//GEN-END:variables
}
