/*
 * Copyright (C) 2013 Thiago Henque Bonotto da Silva & Gustavo Constante
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package poo;

//<editor-fold defaultstate="collapsed" desc="Import's">
import poo.Personagens.Personagem;
//</editor-fold>

/**
 * Classe que atualiza a tela onde ficam indicados os personagens que estão sendo escolhidos
 * 
 * @author Thiago Henrique Bonotto
 * @author Gustavo Constante
 * 
 */
public class PickMenuDown extends javax.swing.JPanel {

    GUIMain parent;
    int n = 1;

    /**
     * Método que modifica os icones e nomes do PickMenuDown para os 
     * dos personagens selecionados.
     * 
     * @param p
     */
    public void addMenuPokemon(Personagem p) {
        jBVoltar.setEnabled(true);
        switch (n) {
            case 1:
                jBEscolhido1.setEnabled(true);
                jBEscolhido1.setIcon(p.getIcon_escolha());
                jLEscolhido1.setText(p.getNome());
                n++;
                break;
            case 2:
                jBEscolhido2.setEnabled(true);
                jBEscolhido2.setIcon(p.getIcon_escolha());
                jLEscolhido2.setText(p.getNome());
                n++;
                break;
            case 3:
                jBEscolhido3.setEnabled(true);
                jBEscolhido3.setIcon(p.getIcon_escolha());
                jLEscolhido3.setText(p.getNome());
                n++;
                break;
            case 4:
                jBEscolhido4.setEnabled(true);
                jBEscolhido4.setIcon(p.getIcon_escolha());
                jLEscolhido4.setText(p.getNome());
                n++;
                break;
            case 5:
                jBEscolhido5.setEnabled(true);
                jBEscolhido5.setIcon(p.getIcon_escolha());
                jLEscolhido5.setText(p.getNome());
                n++;
                break;
            case 6:
                jBEscolhido6.setEnabled(true);
                jBEscolhido6.setIcon(p.getIcon_escolha());
                jLEscolhido6.setText(p.getNome());
                jBEnviarPersonagem.setEnabled(true);
                n++;
                break;
        }
    }

//<editor-fold defaultstate="collapsed" desc="Método que cria uma nova Tela  de PickMenuDown">
    /**
     * Atualiza a tela incial do jogo para a tela de PickDownMenu
     *
     * @param p Recebe uma referencia ao pai.
     */
    public PickMenuDown(GUIMain p) {
        initComponents();
        this.parent = p;

    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEscolhidos = new javax.swing.JPanel();
        jBEscolhido1 = new javax.swing.JButton();
        jBEscolhido2 = new javax.swing.JButton();
        jBEscolhido3 = new javax.swing.JButton();
        jBEscolhido4 = new javax.swing.JButton();
        jBEscolhido5 = new javax.swing.JButton();
        jBEnviarPersonagem = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jBEscolhido6 = new javax.swing.JButton();
        jLEscolhido1 = new javax.swing.JLabel();
        jLEscolhido2 = new javax.swing.JLabel();
        jLEscolhido3 = new javax.swing.JLabel();
        jLEscolhido4 = new javax.swing.JLabel();
        jLEscolhido5 = new javax.swing.JLabel();
        jLEscolhido6 = new javax.swing.JLabel();

        jPEscolhidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBEscolhido1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pokebola.png"))); // NOI18N
        jBEscolhido1.setEnabled(false);
        jBEscolhido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhido1ActionPerformed(evt);
            }
        });

        jBEscolhido2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pokebola.png"))); // NOI18N
        jBEscolhido2.setEnabled(false);

        jBEscolhido3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pokebola.png"))); // NOI18N
        jBEscolhido3.setEnabled(false);

        jBEscolhido4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pokebola.png"))); // NOI18N
        jBEscolhido4.setEnabled(false);

        jBEscolhido5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pokebola.png"))); // NOI18N
        jBEscolhido5.setEnabled(false);

        jBEnviarPersonagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBEnviarPersonagem.setText("Enviar");
        jBEnviarPersonagem.setEnabled(false);
        jBEnviarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarPersonagemActionPerformed(evt);
            }
        });

        jBVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBVoltar.setText("Limpar");
        jBVoltar.setEnabled(false);
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBEscolhido6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pokebola.png"))); // NOI18N
        jBEscolhido6.setEnabled(false);

        javax.swing.GroupLayout jPEscolhidosLayout = new javax.swing.GroupLayout(jPEscolhidos);
        jPEscolhidos.setLayout(jPEscolhidosLayout);
        jPEscolhidosLayout.setHorizontalGroup(
            jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEscolhido1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEscolhido1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBEscolhido2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLEscolhido2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEscolhido3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVoltar)
                    .addComponent(jBEscolhido3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEscolhidosLayout.createSequentialGroup()
                        .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEscolhido4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEscolhido4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEscolhido5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEscolhido5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEscolhido6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEscolhido6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBEnviarPersonagem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEscolhidosLayout.setVerticalGroup(
            jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEscolhidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBEscolhido3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhido1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEscolhido1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEscolhido2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEscolhido3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEscolhido4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEscolhido5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEscolhido6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEscolhidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVoltar)
                    .addComponent(jBEnviarPersonagem)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEscolhidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPEscolhidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

//Sequencia de Ações ao apertar o botão Enviar da Tela de PickMenuDown
    private void jBEnviarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarPersonagemActionPerformed
        // TODO add your handling code here:
        jBEnviarPersonagem.setEnabled(false);
        jBVoltar.setEnabled(false);
        jBEscolhido1.setDisabledIcon(jBEscolhido1.getIcon());
        jBEscolhido1.setEnabled(false);
        jBEscolhido2.setDisabledIcon(jBEscolhido2.getIcon());
        jBEscolhido2.setEnabled(false);
        jBEscolhido3.setDisabledIcon(jBEscolhido3.getIcon());
        jBEscolhido3.setEnabled(false);
        jBEscolhido4.setDisabledIcon(jBEscolhido4.getIcon());
        jBEscolhido4.setEnabled(false);
        jBEscolhido5.setDisabledIcon(jBEscolhido5.getIcon());
        jBEscolhido5.setEnabled(false);
        jBEscolhido6.setDisabledIcon(jBEscolhido6.getIcon());
        jBEscolhido6.setEnabled(false);
        parent.enviaPick();

    }//GEN-LAST:event_jBEnviarPersonagemActionPerformed

//Desabilita a imagem do Personagem ao ser clicado
    private void jBEscolhido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEscolhido1ActionPerformed

//Habilita os Personagens ja selecionados e reseta 
    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        n = 1;
        jBVoltar.setEnabled(false);
        jBEnviarPersonagem.setEnabled(false);
        jBEscolhido1.setEnabled(false);
        jLEscolhido1.setText("");
        jBEscolhido2.setEnabled(false);
        jLEscolhido2.setText("");
        jBEscolhido3.setEnabled(false);
        jLEscolhido3.setText("");
        jBEscolhido4.setEnabled(false);
        jLEscolhido4.setText("");
        jBEscolhido5.setEnabled(false);
        jLEscolhido5.setText("");
        jBEscolhido6.setEnabled(false);
        jLEscolhido6.setText("");
        parent.resetaPick();


    }//GEN-LAST:event_jBVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEnviarPersonagem;
    private javax.swing.JButton jBEscolhido1;
    private javax.swing.JButton jBEscolhido2;
    private javax.swing.JButton jBEscolhido3;
    private javax.swing.JButton jBEscolhido4;
    private javax.swing.JButton jBEscolhido5;
    private javax.swing.JButton jBEscolhido6;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLEscolhido1;
    private javax.swing.JLabel jLEscolhido2;
    private javax.swing.JLabel jLEscolhido3;
    private javax.swing.JLabel jLEscolhido4;
    private javax.swing.JLabel jLEscolhido5;
    private javax.swing.JLabel jLEscolhido6;
    private javax.swing.JPanel jPEscolhidos;
    // End of variables declaration//GEN-END:variables
}
